### ISSUE TITLE
s/ß in "Die Tollen Fußballstars"

### ISSUE THREAD

**Issue by felixheck** [codeofsumit/nostalgie-quiz#21]
The track "Die tollen Fussballstars" does not accep "ß" instead of the doubled "s"  – has ruined my highscore ;)

**Comment by codeofsumit** [comment]
but it accepts "Zubasa" :D
Gonna fix it ;)

**Comment by felixheck** [comment]
Cheating w/ insider information :P

**Comment by codeofsumit** [comment]
fixed (added more songs as well)
