### ISSUE TITLE
Timer does not stop while watching video

### ISSUE THREAD

**Issue by felixheck** [codeofsumit/nostalgie-quiz#23]
If I type in the correct answer and watch the video, the timer is still running.
So every time I walk down memory lane it ruins the highscore.

**Comment by codeofsumit** [comment]
what? No... try again. It should stop the timer. What browser is doing this to me.

**Comment by felixheck** [comment]
It was the latest chrome on OSX. Stopping the process and restart the application solves the problem – no frigging idea :O
