### ISSUE TITLE
Align ranking times with tabular digits

### ISSUE THREAD

**Issue by felixheck** [codeofsumit/nostalgie-quiz#24]
The digits of the ranking times are not monospaced, so the alignment looks buggy.
Enable tabular/monospaced digits, if necessary change font:

`font-feature-settings: "tnum"`

**Comment by codeofsumit** [comment]
![image](https://cloud.githubusercontent.com/assets/2399810/17028240/3cd36258-4f67-11e6-9886-223e4c680fbf.png)

will be fixed soon
